version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: 1emd/foodgram_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: 1emd/foodgram_frontend
    volumes:
      - frontend_volume:/app/build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - frontend_volume:/usr/share/nginx/html/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend

volumes:
  frontend_volume:
  static_value:
  media_value:
